variables:
  DOCKER_PUBLISH_ENABLED: 'false'

include:
  - project: 'vivarium/th2/pipelines'
    ref: master
    file: '/.gitlab-ci-common.yml'

build:
  extends: .build-template
  variables:
    DOCKER_INTERMEDIATE_TAG: "${CI_COMMIT_SHA}"
    DOCKER_BUILD_ARGS: >-
      --build-arg nexus_url=${NEXUS_URL}
      --build-arg nexus_user=${NEXUS_USER}
      --build-arg nexus_password=${NEXUS_PASS}
      --build-arg pypi_repository_url=${PYPI_REPOSITORY_URL}
      --build-arg pypi_user=${PYPI_USER}
      --build-arg pypi_password=${PYPI_PASSWORD}
  dependencies:
    - makeMetaEnv
